# Generated by Django 3.1.6 on 2021-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('audio', models.FileField(upload_to='audio')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
